---

- hosts: client1
  become: true
  tasks:
    - name: start apache2
      service: name=apache2 state=started 


- hosts: client2
  become: true
  tasks:
    - name: start nginx
      service: name=nginx state=started 
 
...
